// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123222942_TablesPosteAdvantagesBonusesAllowancesCompensation")]
    partial class TablesPosteAdvantagesBonusesAllowancesCompensation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP.Models.AdvantageType", b =>
                {
                    b.Property<int>("AdvantageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvantageTypeId"));

                    b.Property<string>("AdvantageTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdvantageTypeId");

                    b.ToTable("AdvantageTypes");
                });

            modelBuilder.Entity("ERP.Models.AllowanceType", b =>
                {
                    b.Property<int>("AllowanceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllowanceTypeId"));

                    b.Property<string>("AllowanceTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AllowanceTypeId");

                    b.ToTable("AllowanceTypes");
                });

            modelBuilder.Entity("ERP.Models.BonusType", b =>
                {
                    b.Property<int>("BonusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BonusTypeId"));

                    b.Property<string>("BonusTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BonusTypeId");

                    b.ToTable("BonusTypes");
                });

            modelBuilder.Entity("ERP.Models.CompensationPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CompensationPackages");
                });

            modelBuilder.Entity("ERP.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PosteId")
                        .HasColumnType("int");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PosteId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAdvantage", b =>
                {
                    b.Property<int>("EmployeeAdvantageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAdvantageId"));

                    b.Property<int>("AdvantageTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CompensationPackageId")
                        .HasColumnType("int");

                    b.Property<string>("EligibilityRule")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeAdvantageId");

                    b.HasIndex("AdvantageTypeId");

                    b.HasIndex("CompensationPackageId", "AdvantageTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeAdvantages");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAllowance", b =>
                {
                    b.Property<int>("EmployeeAllowanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeAllowanceId"));

                    b.Property<int>("AllowanceTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompensationPackageId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeAllowanceId");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("CompensationPackageId", "AllowanceTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeAllowances");
                });

            modelBuilder.Entity("ERP.Models.EmployeeBonus", b =>
                {
                    b.Property<int>("EmployeeBonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeBonusId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BonusRule")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BonusTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CompensationPackageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExceptional")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPerformanceBased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeBonusId");

                    b.HasIndex("BonusTypeId");

                    b.HasIndex("CompensationPackageId", "BonusTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeBonuses");
                });

            modelBuilder.Entity("ERP.Models.Poste", b =>
                {
                    b.Property<int>("PosteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PosteId"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MinimumBaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PosteId");

                    b.ToTable("Postes");
                });

            modelBuilder.Entity("ERP.Models.CompensationPackage", b =>
                {
                    b.HasOne("ERP.Models.Employe", "Employee")
                        .WithMany("CompensationPackages")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP.Models.Employe", b =>
                {
                    b.HasOne("ERP.Models.Poste", "Poste")
                        .WithMany("Employees")
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAdvantage", b =>
                {
                    b.HasOne("ERP.Models.AdvantageType", "AdvantageType")
                        .WithMany()
                        .HasForeignKey("AdvantageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.CompensationPackage", "CompensationPackage")
                        .WithMany("Advantages")
                        .HasForeignKey("CompensationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvantageType");

                    b.Navigation("CompensationPackage");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAllowance", b =>
                {
                    b.HasOne("ERP.Models.AllowanceType", "AllowanceType")
                        .WithMany()
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.CompensationPackage", "CompensationPackage")
                        .WithMany("Allowances")
                        .HasForeignKey("CompensationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowanceType");

                    b.Navigation("CompensationPackage");
                });

            modelBuilder.Entity("ERP.Models.EmployeeBonus", b =>
                {
                    b.HasOne("ERP.Models.BonusType", "BonusType")
                        .WithMany()
                        .HasForeignKey("BonusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.CompensationPackage", "CompensationPackage")
                        .WithMany("Bonuses")
                        .HasForeignKey("CompensationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusType");

                    b.Navigation("CompensationPackage");
                });

            modelBuilder.Entity("ERP.Models.CompensationPackage", b =>
                {
                    b.Navigation("Advantages");

                    b.Navigation("Allowances");

                    b.Navigation("Bonuses");
                });

            modelBuilder.Entity("ERP.Models.Employe", b =>
                {
                    b.Navigation("CompensationPackages");
                });

            modelBuilder.Entity("ERP.Models.Poste", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
