// <auto-generated />
using System;
using ERP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202231649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ERP.Models.AdvantageType", b =>
                {
                    b.Property<int>("AdvantageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdvantageTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AdvantageTypeId");

                    b.ToTable("AdvantageTypes");

                    b.HasData(
                        new
                        {
                            AdvantageTypeId = 1,
                            AdvantageTypeName = "Health Insurance",
                            Description = "Assurance santé complémentaire pour l'employé et sa famille",
                            EligibilityRule = "Full-time employees only",
                            IsTaxable = false,
                            Provider = "Global Health"
                        },
                        new
                        {
                            AdvantageTypeId = 2,
                            AdvantageTypeName = "Gym Membership",
                            Description = "Accès à une salle de sport pour la santé et le bien-être",
                            EligibilityRule = "Available after 3 months of employment",
                            IsTaxable = false,
                            Provider = "FitClub"
                        },
                        new
                        {
                            AdvantageTypeId = 3,
                            AdvantageTypeName = "Company Car",
                            Description = "Mise à disposition d'un véhicule de fonction",
                            EligibilityRule = "Managers only",
                            IsTaxable = true,
                            Provider = "Leasing Co."
                        });
                });

            modelBuilder.Entity("ERP.Models.AllowanceType", b =>
                {
                    b.Property<int>("AllowanceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowanceTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AllowanceTypeId");

                    b.ToTable("AllowanceTypes");

                    b.HasData(
                        new
                        {
                            AllowanceTypeId = 1,
                            AllowanceTypeName = "Transport",
                            Description = "Allocation pour les frais de transport domicile-travail",
                            EligibilityRule = "Tous les employés",
                            IsTaxable = false,
                            Provider = "RATP / Transports publics"
                        },
                        new
                        {
                            AllowanceTypeId = 2,
                            AllowanceTypeName = "Meal",
                            Description = "Allocation pour les repas et restauration",
                            EligibilityRule = "Tous les employés en CDI",
                            IsTaxable = false,
                            Provider = "Restaurant d'entreprise"
                        },
                        new
                        {
                            AllowanceTypeId = 3,
                            AllowanceTypeName = "Housing",
                            Description = "Allocation pour les frais de logement",
                            EligibilityRule = "Sur demande et justification de domicile",
                            IsTaxable = true,
                            Provider = "Auto-géré"
                        },
                        new
                        {
                            AllowanceTypeId = 4,
                            AllowanceTypeName = "Phone",
                            Description = "Allocation pour usage professionnel du téléphone",
                            EligibilityRule = "Employés en contact client ou télétravail",
                            IsTaxable = false,
                            Provider = "Forfait opérateur"
                        });
                });

            modelBuilder.Entity("ERP.Models.BonusType", b =>
                {
                    b.Property<int>("BonusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonusRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("BonusTypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.HasKey("BonusTypeId");

                    b.ToTable("BonusTypes");

                    b.HasData(
                        new
                        {
                            BonusTypeId = 1,
                            BonusRule = "Basée sur les KPIs individuels, entre 0-20% du salaire mensuel",
                            BonusTypeName = "Performance",
                            Description = "Prime basée sur la performance et les objectifs atteints",
                            IsAutomatic = false,
                            IsTaxable = true
                        },
                        new
                        {
                            BonusTypeId = 2,
                            BonusRule = "500-2000€ selon le poste recruté et la durée de permanence",
                            BonusTypeName = "Referral",
                            Description = "Prime pour recommandation et recrutement de candidats",
                            IsAutomatic = false,
                            IsTaxable = true
                        },
                        new
                        {
                            BonusTypeId = 3,
                            BonusRule = "1 mois de salaire minimum, variable selon ancienneté",
                            BonusTypeName = "Year-end",
                            Description = "Prime de fin d'année versée en décembre",
                            IsAutomatic = true,
                            IsTaxable = true
                        });
                });

            modelBuilder.Entity("ERP.Models.CompensationPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("CompensationPackages");
                });

            modelBuilder.Entity("ERP.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CIN")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactUrgence")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFinContrat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LieuNaissance")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationalite")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NombreEnfants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("PosteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SituationFamiliale")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TelephoneUrgence")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeContrat")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PosteId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAdvantage", b =>
                {
                    b.Property<int>("EmployeeAdvantageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdvantageTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompensationPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeAdvantageId");

                    b.HasIndex("AdvantageTypeId");

                    b.HasIndex("CompensationPackageId", "AdvantageTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeAdvantages");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAllowance", b =>
                {
                    b.Property<int>("EmployeeAllowanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllowanceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompensationPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeAllowanceId");

                    b.HasIndex("AllowanceTypeId");

                    b.HasIndex("CompensationPackageId", "AllowanceTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeAllowances");
                });

            modelBuilder.Entity("ERP.Models.EmployeeBonus", b =>
                {
                    b.Property<int>("EmployeeBonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AwardedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("BonusRule")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("BonusTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompensationPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExceptional")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPerformanceBased")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeBonusId");

                    b.HasIndex("BonusTypeId");

                    b.HasIndex("CompensationPackageId", "BonusTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeBonuses");
                });

            modelBuilder.Entity("ERP.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InventoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EquipmentId");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            AcquisitionDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Apple",
                            EquipmentTypeId = 1,
                            InventoryCode = "LAP-001",
                            Model = "MacBook Pro 14\" M3",
                            Name = "MacBook Pro 14\"",
                            PurchasePrice = 2499.00m,
                            SerialNumber = "C02X12345678",
                            Status = 0,
                            Supplier = "Apple Store",
                            WarrantyEndDate = new DateTime(2028, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 2,
                            AcquisitionDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Lenovo",
                            EquipmentTypeId = 1,
                            InventoryCode = "LAP-002",
                            Model = "ThinkPad X1 Carbon Gen 11",
                            Name = "ThinkPad X1 Carbon",
                            PurchasePrice = 1899.00m,
                            SerialNumber = "PF2ABCD1234",
                            Status = 0,
                            Supplier = "Lenovo Direct",
                            WarrantyEndDate = new DateTime(2028, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 3,
                            AcquisitionDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Dell",
                            EquipmentTypeId = 1,
                            InventoryCode = "LAP-003",
                            Model = "Latitude 5540",
                            Name = "Dell Latitude 5540",
                            PurchasePrice = 1299.00m,
                            SerialNumber = "DELL12345ABC",
                            Status = 0,
                            Supplier = "Dell Business",
                            WarrantyEndDate = new DateTime(2028, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 4,
                            AcquisitionDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Dell",
                            EquipmentTypeId = 2,
                            InventoryCode = "DES-001",
                            Model = "OptiPlex 7010",
                            Name = "Dell OptiPlex 7010",
                            PurchasePrice = 899.00m,
                            SerialNumber = "OPTIPLEX7890",
                            Status = 0,
                            Supplier = "Dell Business",
                            WarrantyEndDate = new DateTime(2027, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 5,
                            AcquisitionDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Apple",
                            EquipmentTypeId = 3,
                            InventoryCode = "PHN-001",
                            Model = "iPhone 15 Pro 256GB",
                            Name = "iPhone 15 Pro",
                            PurchasePrice = 1199.00m,
                            SerialNumber = "DQWERTY12345",
                            Status = 0,
                            Supplier = "Apple Store",
                            WarrantyEndDate = new DateTime(2027, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 6,
                            AcquisitionDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Samsung",
                            EquipmentTypeId = 3,
                            InventoryCode = "PHN-002",
                            Model = "Galaxy S24 Ultra",
                            Name = "Samsung Galaxy S24",
                            PurchasePrice = 1099.00m,
                            SerialNumber = "RFCM12345678",
                            Status = 0,
                            Supplier = "Samsung Business",
                            WarrantyEndDate = new DateTime(2027, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 7,
                            AcquisitionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "HID",
                            EquipmentTypeId = 4,
                            InventoryCode = "BAD-001",
                            Model = "iCLASS SE",
                            Name = "Badge Accès Principal",
                            PurchasePrice = 15.00m,
                            SerialNumber = "BADGE-001",
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 8,
                            AcquisitionDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "HID",
                            EquipmentTypeId = 4,
                            InventoryCode = "BAD-002",
                            Model = "iCLASS SE",
                            Name = "Badge Accès Principal",
                            PurchasePrice = 15.00m,
                            SerialNumber = "BADGE-002",
                            Status = 0
                        },
                        new
                        {
                            EquipmentId = 9,
                            AcquisitionDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Dell",
                            EquipmentTypeId = 10,
                            InventoryCode = "MON-001",
                            Model = "UltraSharp U2722D",
                            Name = "Dell UltraSharp 27\"",
                            PurchasePrice = 549.00m,
                            SerialNumber = "MONITOR-001",
                            Status = 0,
                            Supplier = "Dell Business",
                            WarrantyEndDate = new DateTime(2027, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            EquipmentId = 10,
                            AcquisitionDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "LG",
                            EquipmentTypeId = 10,
                            InventoryCode = "MON-002",
                            Model = "34WN80C-B",
                            Name = "LG 34\" Curved",
                            PurchasePrice = 699.00m,
                            SerialNumber = "MONITOR-002",
                            Status = 0,
                            Supplier = "Amazon Business",
                            WarrantyEndDate = new DateTime(2027, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ERP.Models.EquipmentAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConditionAtAssignment")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConditionAtReturn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnNotes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("AssignmentId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentAssignments");
                });

            modelBuilder.Entity("ERP.Models.EquipmentType", b =>
                {
                    b.Property<int>("EquipmentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstimatedLifespanMonths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresMaintenance")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipmentTypeId");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            EquipmentTypeId = 1,
                            Category = "Informatique",
                            Description = "Ordinateur portable professionnel pour le travail",
                            EstimatedLifespanMonths = 48,
                            Name = "Ordinateur Portable",
                            RequiresMaintenance = true
                        },
                        new
                        {
                            EquipmentTypeId = 2,
                            Category = "Informatique",
                            Description = "Ordinateur fixe avec écran pour le bureau",
                            EstimatedLifespanMonths = 60,
                            Name = "Ordinateur de Bureau",
                            RequiresMaintenance = true
                        },
                        new
                        {
                            EquipmentTypeId = 3,
                            Category = "Informatique",
                            Description = "Smartphone professionnel",
                            EstimatedLifespanMonths = 24,
                            Name = "Téléphone Mobile",
                            RequiresMaintenance = false
                        },
                        new
                        {
                            EquipmentTypeId = 4,
                            Category = "Sécurité",
                            Description = "Badge d'accès aux locaux de l'entreprise",
                            Name = "Badge d'accès",
                            RequiresMaintenance = false
                        },
                        new
                        {
                            EquipmentTypeId = 5,
                            Category = "Sécurité",
                            Description = "Trousseau de clés pour accès aux bureaux",
                            Name = "Clés de bureau",
                            RequiresMaintenance = false
                        },
                        new
                        {
                            EquipmentTypeId = 6,
                            Category = "Vêtements",
                            Description = "Uniforme ou vêtements de travail fournis",
                            EstimatedLifespanMonths = 12,
                            Name = "Tenue de travail",
                            RequiresMaintenance = false
                        },
                        new
                        {
                            EquipmentTypeId = 7,
                            Category = "Sécurité",
                            Description = "Casque, gants, lunettes de protection, etc.",
                            EstimatedLifespanMonths = 12,
                            Name = "Équipement de sécurité",
                            RequiresMaintenance = false
                        },
                        new
                        {
                            EquipmentTypeId = 8,
                            Category = "Mobilier",
                            Description = "Bureau, chaise ergonomique, etc.",
                            EstimatedLifespanMonths = 120,
                            Name = "Mobilier de bureau",
                            RequiresMaintenance = false
                        },
                        new
                        {
                            EquipmentTypeId = 9,
                            Category = "Transport",
                            Description = "Voiture ou véhicule de fonction",
                            EstimatedLifespanMonths = 60,
                            Name = "Véhicule de service",
                            RequiresMaintenance = true
                        },
                        new
                        {
                            EquipmentTypeId = 10,
                            Category = "Informatique",
                            Description = "Moniteur additionnel pour le poste de travail",
                            EstimatedLifespanMonths = 72,
                            Name = "Écran supplémentaire",
                            RequiresMaintenance = false
                        });
                });

            modelBuilder.Entity("ERP.Models.Poste", b =>
                {
                    b.Property<int>("PosteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumBaseSalary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PosteId");

                    b.ToTable("Postes");

                    b.HasData(
                        new
                        {
                            PosteId = 1,
                            Department = "IT",
                            MinimumBaseSalary = 2500m,
                            Title = "Junior Developer"
                        },
                        new
                        {
                            PosteId = 2,
                            Department = "IT",
                            MinimumBaseSalary = 5000m,
                            Title = "Senior Developer"
                        },
                        new
                        {
                            PosteId = 3,
                            Department = "IT",
                            MinimumBaseSalary = 4000m,
                            Title = "Full Stack Developer"
                        },
                        new
                        {
                            PosteId = 4,
                            Department = "IT",
                            MinimumBaseSalary = 4500m,
                            Title = "DevOps Engineer"
                        },
                        new
                        {
                            PosteId = 5,
                            Department = "IT",
                            MinimumBaseSalary = 7000m,
                            Title = "IT Manager"
                        },
                        new
                        {
                            PosteId = 6,
                            Department = "IT",
                            MinimumBaseSalary = 3500m,
                            Title = "System Administrator"
                        },
                        new
                        {
                            PosteId = 7,
                            Department = "IT",
                            MinimumBaseSalary = 3000m,
                            Title = "QA Engineer"
                        },
                        new
                        {
                            PosteId = 8,
                            Department = "Human Resources",
                            MinimumBaseSalary = 3000m,
                            Title = "HR Specialist"
                        },
                        new
                        {
                            PosteId = 9,
                            Department = "Human Resources",
                            MinimumBaseSalary = 2800m,
                            Title = "Recruiter"
                        },
                        new
                        {
                            PosteId = 10,
                            Department = "Human Resources",
                            MinimumBaseSalary = 5500m,
                            Title = "HR Manager"
                        },
                        new
                        {
                            PosteId = 11,
                            Department = "Human Resources",
                            MinimumBaseSalary = 3200m,
                            Title = "Training Coordinator"
                        },
                        new
                        {
                            PosteId = 12,
                            Department = "Human Resources",
                            MinimumBaseSalary = 3000m,
                            Title = "Payroll Specialist"
                        },
                        new
                        {
                            PosteId = 13,
                            Department = "Finance",
                            MinimumBaseSalary = 3200m,
                            Title = "Accountant"
                        },
                        new
                        {
                            PosteId = 14,
                            Department = "Finance",
                            MinimumBaseSalary = 4000m,
                            Title = "Financial Analyst"
                        },
                        new
                        {
                            PosteId = 15,
                            Department = "Finance",
                            MinimumBaseSalary = 4500m,
                            Title = "Senior Accountant"
                        },
                        new
                        {
                            PosteId = 16,
                            Department = "Finance",
                            MinimumBaseSalary = 6000m,
                            Title = "Finance Manager"
                        },
                        new
                        {
                            PosteId = 17,
                            Department = "Sales",
                            MinimumBaseSalary = 2500m,
                            Title = "Sales Representative"
                        },
                        new
                        {
                            PosteId = 18,
                            Department = "Sales",
                            MinimumBaseSalary = 5000m,
                            Title = "Sales Manager"
                        },
                        new
                        {
                            PosteId = 19,
                            Department = "Marketing",
                            MinimumBaseSalary = 3200m,
                            Title = "Marketing Specialist"
                        },
                        new
                        {
                            PosteId = 20,
                            Department = "Marketing",
                            MinimumBaseSalary = 4500m,
                            Title = "Digital Marketing Manager"
                        },
                        new
                        {
                            PosteId = 21,
                            Department = "Marketing",
                            MinimumBaseSalary = 2800m,
                            Title = "Content Creator"
                        },
                        new
                        {
                            PosteId = 22,
                            Department = "Operations",
                            MinimumBaseSalary = 5500m,
                            Title = "Operations Manager"
                        },
                        new
                        {
                            PosteId = 23,
                            Department = "Operations",
                            MinimumBaseSalary = 4500m,
                            Title = "Project Manager"
                        },
                        new
                        {
                            PosteId = 24,
                            Department = "Operations",
                            MinimumBaseSalary = 2200m,
                            Title = "Administrative Assistant"
                        },
                        new
                        {
                            PosteId = 25,
                            Department = "Operations",
                            MinimumBaseSalary = 3800m,
                            Title = "Business Analyst"
                        },
                        new
                        {
                            PosteId = 26,
                            Department = "Customer Support",
                            MinimumBaseSalary = 2400m,
                            Title = "Customer Support Agent"
                        },
                        new
                        {
                            PosteId = 27,
                            Department = "Customer Support",
                            MinimumBaseSalary = 4200m,
                            Title = "Customer Support Manager"
                        },
                        new
                        {
                            PosteId = 28,
                            Department = "Customer Support",
                            MinimumBaseSalary = 3000m,
                            Title = "Technical Support Specialist"
                        });
                });

            modelBuilder.Entity("ERP.Models.CompensationPackage", b =>
                {
                    b.HasOne("ERP.Models.Employe", "Employee")
                        .WithMany("CompensationPackages")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ERP.Models.Employe", b =>
                {
                    b.HasOne("ERP.Models.Poste", "Poste")
                        .WithMany("Employees")
                        .HasForeignKey("PosteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Poste");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAdvantage", b =>
                {
                    b.HasOne("ERP.Models.AdvantageType", "AdvantageType")
                        .WithMany()
                        .HasForeignKey("AdvantageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.CompensationPackage", "CompensationPackage")
                        .WithMany("Advantages")
                        .HasForeignKey("CompensationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdvantageType");

                    b.Navigation("CompensationPackage");
                });

            modelBuilder.Entity("ERP.Models.EmployeeAllowance", b =>
                {
                    b.HasOne("ERP.Models.AllowanceType", "AllowanceType")
                        .WithMany()
                        .HasForeignKey("AllowanceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.CompensationPackage", "CompensationPackage")
                        .WithMany("Allowances")
                        .HasForeignKey("CompensationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AllowanceType");

                    b.Navigation("CompensationPackage");
                });

            modelBuilder.Entity("ERP.Models.EmployeeBonus", b =>
                {
                    b.HasOne("ERP.Models.BonusType", "BonusType")
                        .WithMany()
                        .HasForeignKey("BonusTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP.Models.CompensationPackage", "CompensationPackage")
                        .WithMany("Bonuses")
                        .HasForeignKey("CompensationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BonusType");

                    b.Navigation("CompensationPackage");
                });

            modelBuilder.Entity("ERP.Models.Equipment", b =>
                {
                    b.HasOne("ERP.Models.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("ERP.Models.EquipmentAssignment", b =>
                {
                    b.HasOne("ERP.Models.Employe", "Employee")
                        .WithMany("EquipmentAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERP.Models.Equipment", "Equipment")
                        .WithMany("Assignments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("ERP.Models.CompensationPackage", b =>
                {
                    b.Navigation("Advantages");

                    b.Navigation("Allowances");

                    b.Navigation("Bonuses");
                });

            modelBuilder.Entity("ERP.Models.Employe", b =>
                {
                    b.Navigation("CompensationPackages");

                    b.Navigation("EquipmentAssignments");
                });

            modelBuilder.Entity("ERP.Models.Equipment", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("ERP.Models.EquipmentType", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("ERP.Models.Poste", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
